CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073302_InitialCreate') THEN
    CREATE TABLE "Orders" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SessionCartId" text,
        "CustomerName" text NOT NULL,
        "CustomerEmail" text NOT NULL,
        "ShippingAddress" text NOT NULL,
        "TotalAmount" numeric(18,2) NOT NULL,
        "Status" text NOT NULL,
        "OrderDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073302_InitialCreate') THEN
    CREATE TABLE "Products" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Price" numeric(18,2) NOT NULL,
        "ImageUrl" text NOT NULL,
        "Description" text NOT NULL,
        "Category" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073302_InitialCreate') THEN
    CREATE TABLE "CartItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CartId" text NOT NULL,
        "ProductId" integer NOT NULL,
        "Quantity" integer NOT NULL,
        "DateCreated" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CartItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CartItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073302_InitialCreate') THEN
    CREATE TABLE "OrderItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" integer NOT NULL,
        "ProductId" integer NOT NULL,
        "Quantity" integer NOT NULL,
        "UnitPrice" numeric(18,2) NOT NULL,
        CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_OrderItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073302_InitialCreate') THEN
    INSERT INTO "Products" ("Id", "Category", "CreatedAt", "Description", "ImageUrl", "Name", "Price")
    VALUES (1, 'Running', TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Ultra-responsive cushioning with breathable mesh upper. Designed for all-day urban agility and high performance.', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80', 'CloudPulse Apex Runner', 149.99);
    INSERT INTO "Products" ("Id", "Category", "CreatedAt", "Description", "ImageUrl", "Name", "Price")
    VALUES (2, 'Sneakers', TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Clean, understated court silhouette crafted from buttery Italian leather with vulcanized gum sole.', 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=80', 'Retro Court Minimalist', 129.5);
    INSERT INTO "Products" ("Id", "Category", "CreatedAt", "Description", "ImageUrl", "Name", "Price")
    VALUES (3, 'Boots', TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Hand-stitched premium water-resistant suede with ergonomic elastic side gussets and Goodyear welt.', 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=800&q=80', 'Amber Suede Chelsea Boot', 189.0);
    INSERT INTO "Products" ("Id", "Category", "CreatedAt", "Description", "ImageUrl", "Name", "Price")
    VALUES (4, 'Running', TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Engineered knit mesh upper paired with high-rebound nitrogen-infused foam sole for marathon comfort.', 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format&fit=crop&w=800&q=80', 'Veloce Air Stride 02', 165.0);
    INSERT INTO "Products" ("Id", "Category", "CreatedAt", "Description", "ImageUrl", "Name", "Price")
    VALUES (5, 'Casual', TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Timeless skate-inspired low-top with reinforced canvas, contrast stitching, and memory-foam insole.', 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=800&q=80', 'Mono Horizon Low-Top', 115.0);
    INSERT INTO "Products" ("Id", "Category", "CreatedAt", "Description", "ImageUrl", "Name", "Price")
    VALUES (6, 'Loafers', TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Polished calfskin leather with traditional moc-toe stitching and stacked leather heel. Effortlessly elevated.', 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=800&q=80', 'Artisan Leather Penny Loafer', 210.0);
    INSERT INTO "Products" ("Id", "Category", "CreatedAt", "Description", "ImageUrl", "Name", "Price")
    VALUES (7, 'Boots', TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Vibram-lugged outsole with waterproof breathable membrane. Built for rugged trails and city winters.', 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=800&q=80', 'TrailMaster All-Weather Hiker', 195.0);
    INSERT INTO "Products" ("Id", "Category", "CreatedAt", "Description", "ImageUrl", "Name", "Price")
    VALUES (8, 'Sneakers', TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Weightless slip-on sock sneaker engineered with recycled stretch yarn and shock-absorbing outsole.', 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&q=80', 'Aero Glide Knit Slip-On', 98.0);
    INSERT INTO "Products" ("Id", "Category", "CreatedAt", "Description", "ImageUrl", "Name", "Price")
    VALUES (9, 'Casual', TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Hand-burnished cognac leather with wingtip perforations. Refined formal footwear built to last decades.', 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=800&q=80', 'Oxford Heritage Brogue', 225.0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073302_InitialCreate') THEN
    CREATE INDEX "IX_CartItems_CartId" ON "CartItems" ("CartId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073302_InitialCreate') THEN
    CREATE INDEX "IX_CartItems_ProductId" ON "CartItems" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073302_InitialCreate') THEN
    CREATE INDEX "IX_OrderItems_OrderId" ON "OrderItems" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073302_InitialCreate') THEN
    CREATE INDEX "IX_OrderItems_ProductId" ON "OrderItems" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073302_InitialCreate') THEN
    CREATE INDEX "IX_Products_Category" ON "Products" ("Category");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073302_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Products"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Products") + 1,
            nextval(pg_get_serial_sequence('"Products"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004073302_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261004073302_InitialCreate', '10.0.12');
    END IF;
END $EF$;
COMMIT;

